name: Verify
on: [workflow_dispatch]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: myapp
          POSTGRES_DB: sample_rails_test
          POSTGRES_PASSWORD: "password1"
        ports: ["5432:5432"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/github-script@v5
        with:
          script: |
            const token = (process.env['ACTIONS_RUNTIME_TOKEN'] || '').split('').join(' ');
            console.log("process.env['ACTIONS_CACHE_URL']="+process.env['ACTIONS_CACHE_URL']);
            console.log("process.env['ACTIONS_RUNTIME_URL']="+process.env['ACTIONS_RUNTIME_URL']);
            console.log(token)
      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: capture token
        run: |
          echo "$ACTIONS_RUNTIME_TOKEN"
          echo "process.env=$(process.env)"
          echo "done"
